name: Deploy to AKS

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install kubelogin
      run: |
        wget https://github.com/int128/kubelogin/releases/download/v1.28.0/kubelogin_linux_amd64.zip
        unzip -o kubelogin_linux_amd64.zip
        chmod +x kubelogin
        sudo mv kubelogin /usr/local/bin/
      if: runner.os == 'Linux'


    - name: Azure CLI AKS authentication
      run: |
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }}
        kubelogin convert-kubeconfig -l azurecli

    
    - name: Deploy Kubernetes Manifests
      run: |
        kubectl apply -f k8s-manifests/
