name: Deploy to AKS

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

env:
  DEPLOYMENT_MANIFEST_PATH: "k8s-manifests/"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        client-id: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
        tenant-id: ${{ secrets.TENANT }}
        subscription-id: ${{ secrets.SUBSCRIPTION }}

    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        ubelogin-version: 'v0.0.25'

    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

    - name: Deploys application
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}

