name: Deploy to AKS

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install asdf
      run: |
        sudo apt update && sudo apt install snapd
      if: runner.os == 'Linux'

    - name: Install kubelogin plugin
      run: sudo snap install kubelogin
      
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      if: runner.os == 'Linux'

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI AKS authentication
      run: |
        az account set --subscription ${{ secrets.SUBSCRIPTION }}
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }}
        kubelogin convert-kubeconfig -l azurecli
        
    - name: Deploy Kubernetes Manifests
      run: |
        kubectl apply -f k8s-manifests/
